# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "33d20dc4177978d411eaae3dd44ce65f"
application_url = "https://wait-utilize-explore-wichita.trycloudflare.com"
embedded = true
name = "test-tailwind-app"
handle = "test-tailwind-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://wait-utilize-explore-wichita.trycloudflare.com/auth/callback",
  "https://wait-utilize-explore-wichita.trycloudflare.com/auth/shopify/callback",
  "https://wait-utilize-explore-wichita.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
